From: Ren√© Dudfield <renesd@gmail.com>
Subject: In set_error get_error tests ignore first error. Could be anything.
Origin: https://github.com/pygame/pygame/pull/443.patch
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861254

---
 test/base_test.py | 16 ++--------------
 1 file changed, 2 insertions(+), 14 deletions(-)

diff --git a/test/base_test.py b/test/base_test.py
index da51928f..3e3a81f9 100644
--- a/test/base_test.py
+++ b/test/base_test.py
@@ -573,14 +573,8 @@ def test_get_error(self):
           # call this function.
           #
 
+        # The first error could be all sorts of nonsense or empty.
         e = pygame.get_error()
-        self.assertTrue(e == "" or
-                        # This may be returned by SDL_mixer built with
-                        # FluidSynth support. Setting environment variable
-                        # SDL_SOUNDFONTS to the path of a valid sound font
-                        # file removes the error message.
-                        e == "No SoundFonts have been requested",
-                        e)
         pygame.set_error("hi")
         self.assertEqual(pygame.get_error(), "hi")
         pygame.set_error("")
@@ -590,14 +584,8 @@ def test_get_error(self):
 
     def test_set_error(self):
 
+        # The first error could be all sorts of nonsense or empty.
         e = pygame.get_error()
-        self.assertTrue(e == "" or
-                        # This may be returned by SDL_mixer built with
-                        # FluidSynth support. Setting environment variable
-                        # SDL_SOUNDFONTS to the path of a valid sf2 file
-                        # removes the error message.
-                        e == "No SoundFonts have been requested",
-                        e)
         pygame.set_error("hi")
         self.assertEqual(pygame.get_error(), "hi")
         pygame.set_error("")
